import { useEffect, useState } from 'react';
import { Lightbulb, TrendingUp, AlertTriangle, Target, Sparkles } from 'lucide-react';
import { mockData } from '../lib/mockData';
import { formatTimeAgo } from '../utils/helpers';
import type { AIInsight } from '../types';

export default function AIInsights() {
  const [insights, setInsights] = useState<AIInsight[]>([]);

  useEffect(() => {
    setInsights(mockData.aiInsights);
  }, []);

  const predictions = insights.filter((i) => i.insight_type === 'prediction');
  const trends = insights.filter((i) => i.insight_type === 'trend');
  const recommendations = insights.filter((i) => i.insight_type === 'recommendation');
  const anomalies = insights.filter((i) => i.insight_type === 'anomaly');

  const getInsightIcon = (type: AIInsight['insight_type']) => {
    switch (type) {
      case 'prediction':
        return Target;
      case 'trend':
        return TrendingUp;
      case 'recommendation':
        return Lightbulb;
      case 'anomaly':
        return AlertTriangle;
      default:
        return Sparkles;
    }
  };

  const getInsightColor = (type: AIInsight['insight_type']) => {
    switch (type) {
      case 'prediction':
        return 'bg-blue-500';
      case 'trend':
        return 'bg-green-500';
      case 'recommendation':
        return 'bg-amber-500';
      case 'anomaly':
        return 'bg-red-500';
      default:
        return 'bg-gray-500';
    }
  };

  const getConfidenceColor = (score: number) => {
    if (score >= 0.9) return 'text-green-600 bg-green-50';
    if (score >= 0.7) return 'text-amber-600 bg-amber-50';
    return 'text-red-600 bg-red-50';
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold text-gray-900">AI Insights</h1>
        <p className="text-gray-500 mt-1">
          AI-generated predictions, trends, and recommendations powered by Google Gemini
        </p>
      </div>

      <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 flex items-start space-x-3">
        <Sparkles className="w-5 h-5 text-blue-600 mt-0.5" />
        <div>
          <p className="font-medium text-blue-900">Google Gemini AI Integration</p>
          <p className="text-sm text-blue-700 mt-1">
            These insights are generated by analyzing historical data, current trends, and
            predictive models to help optimize waste management operations.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-2">
            <div className="bg-blue-100 rounded-lg p-3">
              <Target className="w-6 h-6 text-blue-600" />
            </div>
          </div>
          <p className="text-2xl font-bold text-gray-900">{predictions.length}</p>
          <p className="text-sm text-gray-600">Predictions</p>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-2">
            <div className="bg-green-100 rounded-lg p-3">
              <TrendingUp className="w-6 h-6 text-green-600" />
            </div>
          </div>
          <p className="text-2xl font-bold text-gray-900">{trends.length}</p>
          <p className="text-sm text-gray-600">Trends</p>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-2">
            <div className="bg-amber-100 rounded-lg p-3">
              <Lightbulb className="w-6 h-6 text-amber-600" />
            </div>
          </div>
          <p className="text-2xl font-bold text-gray-900">{recommendations.length}</p>
          <p className="text-sm text-gray-600">Recommendations</p>
        </div>

        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
          <div className="flex items-center justify-between mb-2">
            <div className="bg-red-100 rounded-lg p-3">
              <AlertTriangle className="w-6 h-6 text-red-600" />
            </div>
          </div>
          <p className="text-2xl font-bold text-gray-900">{anomalies.length}</p>
          <p className="text-sm text-gray-600">Anomalies</p>
        </div>
      </div>

      <div className="space-y-4">
        {insights.map((insight) => {
          const Icon = getInsightIcon(insight.insight_type);
          return (
            <div
              key={insight.id}
              className="bg-white rounded-lg shadow-sm border border-gray-200 p-6 hover:shadow-md transition-shadow"
            >
              <div className="flex items-start space-x-4">
                <div className={`${getInsightColor(insight.insight_type)} rounded-lg p-3`}>
                  <Icon className="w-6 h-6 text-white" />
                </div>

                <div className="flex-1">
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <h3 className="text-lg font-bold text-gray-900">{insight.title}</h3>
                      <span className="inline-block mt-1 px-3 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full">
                        {insight.insight_type}
                      </span>
                    </div>
                    {insight.confidence_score && (
                      <div
                        className={`px-3 py-1 rounded-lg text-sm font-medium ${getConfidenceColor(
                          insight.confidence_score
                        )}`}
                      >
                        {(insight.confidence_score * 100).toFixed(0)}% confidence
                      </div>
                    )}
                  </div>

                  <p className="text-gray-700 mb-4">{insight.description}</p>

                  <div className="flex flex-wrap gap-4 text-sm text-gray-600">
                    {insight.data_source && <span>Source: {insight.data_source}</span>}
                    {insight.relevant_zone && <span>Zone: {insight.relevant_zone}</span>}
                    {insight.relevant_bin_id && <span>Bin: {insight.relevant_bin_id}</span>}
                    <span>{formatTimeAgo(insight.created_at)}</span>
                  </div>

                  {insight.insight_type === 'recommendation' && (
                    <button className="mt-4 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors text-sm font-medium">
                      Implement Recommendation
                    </button>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {insights.length === 0 && (
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-12 text-center">
          <Sparkles className="w-16 h-16 text-gray-300 mx-auto mb-4" />
          <h3 className="text-lg font-bold text-gray-700 mb-2">No Insights Available</h3>
          <p className="text-gray-500">
            AI insights will appear here as the system analyzes waste management data
          </p>
        </div>
      )}

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h2 className="text-lg font-bold text-gray-900 mb-4">Future Scope Features</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-4 bg-gray-50 rounded-lg">
            <h3 className="font-medium text-gray-900 mb-2">Carbon Footprint Calculator</h3>
            <p className="text-sm text-gray-600">
              Calculate CO2 emissions saved through optimized collection routes and recycling
              efforts
            </p>
          </div>

          <div className="p-4 bg-gray-50 rounded-lg">
            <h3 className="font-medium text-gray-900 mb-2">Predictive Maintenance</h3>
            <p className="text-sm text-gray-600">
              AI-powered alerts for bin and vehicle maintenance needs before failures occur
            </p>
          </div>

          <div className="p-4 bg-gray-50 rounded-lg">
            <h3 className="font-medium text-gray-900 mb-2">Smart City Integration</h3>
            <p className="text-sm text-gray-600">
              Connect with traffic management, weather systems, and other smart city modules
            </p>
          </div>

          <div className="p-4 bg-gray-50 rounded-lg">
            <h3 className="font-medium text-gray-900 mb-2">Advanced Pattern Recognition</h3>
            <p className="text-sm text-gray-600">
              Identify complex waste generation patterns for better resource allocation
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
